# Generated by Django 5.1.3 on 2024-12-03 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('pindex', models.IntegerField(default=0, null=True)),
                ('money', models.IntegerField(default=0, null=True)),
                ('category', models.CharField(default='Bezpartijní', max_length=200, null=True)),
                ('color', models.CharField(max_length=200, null=True)),
                ('marcs', models.IntegerField(default=0, null=True)),
                ('wait_moves', models.IntegerField(default=0, null=True)),
                ('looks_like_stalin', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('on_move', models.BooleanField(default=False)),
                ('skipped', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_starting_money', models.IntegerField(blank=True, default=0, null=True)),
                ('room_name', models.CharField(max_length=200, null=True)),
                ('actual_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.player')),
            ],
        ),
    ]
