# Generated by Django 5.1.3 on 2024-12-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_player_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='category',
            field=models.CharField(choices=[('BEZ', 'Bezpartijní')], default='Bezpartijní', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='game_starting_money',
            field=models.IntegerField(blank=True, default=2000, null=True),
        ),
    ]
