# Generated by Django 5.1.3 on 2024-12-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_player_account_alter_player_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='category',
            field=models.CharField(choices=[('UV', 'Člen Ústředního Výboru'), ('KOM', 'Člen Strany'), ('POL', 'Člen Politbyra ÚV'), ('POS', 'Poslanec'), ('GEN', 'Generální Tajemník ÚV Strany'), ('KAN', 'Kandidát'), ('BEZ', 'Bezpartijní')], default='BEZ', max_length=200, null=True),
        ),
    ]
