# Generated by Django 5.1.3 on 2024-12-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_player_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='nuzky',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='plan_zaminovani',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='propustka',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='proverka',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='vesta',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='category',
            field=models.CharField(choices=[('1-BEZ', 'Bezpartijní'), ('3-KOM', 'Člen Strany'), ('4-POS', 'Poslanec'), ('7-GEN', 'Generální Tajemník ÚV Strany'), ('6-POL', 'Člen Politbyra ÚV'), ('5-UV', 'Člen Ústředního Výboru'), ('2-KAN', 'Kandidát')], default='1-BEZ', max_length=200, null=True),
        ),
    ]
