# Generated by Django 5.1.3 on 2024-12-03 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_player_nuzky_player_plan_zaminovani_player_propustka_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='actual_player',
        ),
        migrations.AddField(
            model_name='player',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.room'),
        ),
        migrations.AlterField(
            model_name='player',
            name='category',
            field=models.CharField(choices=[('6-POL', 'Člen Politbyra ÚV'), ('4-POS', 'Poslanec'), ('3-KOM', 'Člen Strany'), ('5-UV', 'Člen Ústředního Výboru'), ('7-GEN', 'Generální Tajemník ÚV Strany'), ('1-BEZ', 'Bezpartijní'), ('2-KAN', 'Kandidát')], default='1-BEZ', max_length=200, null=True),
        ),
    ]
