# Generated by Django 5.1.3 on 2024-12-03 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_postih_vylepseni_alter_player_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Player', 'verbose_name_plural': 'Players'},
        ),
        migrations.AlterModelOptions(
            name='postih',
            options={'verbose_name': 'Postih', 'verbose_name_plural': 'Postihy'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Room', 'verbose_name_plural': 'Rooms'},
        ),
        migrations.AlterModelOptions(
            name='vylepseni',
            options={'verbose_name': 'Vylepšení', 'verbose_name_plural': 'Vylepšení'},
        ),
        migrations.AlterField(
            model_name='player',
            name='category',
            field=models.CharField(choices=[('7-GEN', 'Generální Tajemník ÚV Strany'), ('3-KOM', 'Člen Strany'), ('5-UV', 'Člen Ústředního Výboru'), ('4-POS', 'Poslanec'), ('2-KAN', 'Kandidát'), ('6-POL', 'Člen Politbyra ÚV'), ('1-BEZ', 'Bezpartijní')], default='1-BEZ', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='postih',
            name='category',
            field=models.CharField(choices=[('7-GEN', 'Generální Tajemník ÚV Strany'), ('3-KOM', 'Člen Strany'), ('5-UV', 'Člen Ústředního Výboru'), ('4-POS', 'Poslanec'), ('2-KAN', 'Kandidát'), ('6-POL', 'Člen Politbyra ÚV'), ('1-BEZ', 'Bezpartijní')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vylepseni',
            name='category',
            field=models.CharField(choices=[('7-GEN', 'Generální Tajemník ÚV Strany'), ('3-KOM', 'Člen Strany'), ('5-UV', 'Člen Ústředního Výboru'), ('4-POS', 'Poslanec'), ('2-KAN', 'Kandidát'), ('6-POL', 'Člen Politbyra ÚV'), ('1-BEZ', 'Bezpartijní')], max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200, null=True)),
                ('message', models.CharField(blank=True, max_length=2000, null=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.player')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
