# Generated by Django 5.1.3 on 2024-12-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_alter_message_player_alter_player_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='name',
        ),
        migrations.AlterField(
            model_name='player',
            name='category',
            field=models.CharField(choices=[('4-POS', 'Poslanec'), ('1-BEZ', 'Bezpartijní'), ('3-KOM', 'Člen Strany'), ('2-KAN', 'Kandidát'), ('6-POL', 'Člen Politbyra ÚV'), ('7-GEN', 'Generální Tajemník ÚV Strany'), ('5-UV', 'Člen Ústředního Výboru')], default='1-BEZ', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='postih',
            name='category',
            field=models.CharField(choices=[('4-POS', 'Poslanec'), ('1-BEZ', 'Bezpartijní'), ('3-KOM', 'Člen Strany'), ('2-KAN', 'Kandidát'), ('6-POL', 'Člen Politbyra ÚV'), ('7-GEN', 'Generální Tajemník ÚV Strany'), ('5-UV', 'Člen Ústředního Výboru')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vylepseni',
            name='category',
            field=models.CharField(choices=[('4-POS', 'Poslanec'), ('1-BEZ', 'Bezpartijní'), ('3-KOM', 'Člen Strany'), ('2-KAN', 'Kandidát'), ('6-POL', 'Člen Politbyra ÚV'), ('7-GEN', 'Generální Tajemník ÚV Strany'), ('5-UV', 'Člen Ústředního Výboru')], max_length=200, null=True),
        ),
    ]
