# Generated by Django 5.1.3 on 2024-12-09 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_alter_player_category_alter_postih_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='actual_player',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='category',
            field=models.CharField(choices=[('5-UV', 'Člen Ústředního Výboru'), ('1-BEZ', 'Bezpartijní'), ('6-POL', 'Člen Politbyra ÚV'), ('4-POS', 'Poslanec'), ('7-GEN', 'Generální Tajemník ÚV Strany'), ('3-KOM', 'Člen Strany'), ('2-KAN', 'Kandidát')], default='1-BEZ', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='postih',
            name='category',
            field=models.CharField(choices=[('5-UV', 'Člen Ústředního Výboru'), ('1-BEZ', 'Bezpartijní'), ('6-POL', 'Člen Politbyra ÚV'), ('4-POS', 'Poslanec'), ('7-GEN', 'Generální Tajemník ÚV Strany'), ('3-KOM', 'Člen Strany'), ('2-KAN', 'Kandidát')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vylepseni',
            name='category',
            field=models.CharField(choices=[('5-UV', 'Člen Ústředního Výboru'), ('1-BEZ', 'Bezpartijní'), ('6-POL', 'Člen Politbyra ÚV'), ('4-POS', 'Poslanec'), ('7-GEN', 'Generální Tajemník ÚV Strany'), ('3-KOM', 'Člen Strany'), ('2-KAN', 'Kandidát')], max_length=200, null=True),
        ),
    ]
