# Generated by Django 5.1.3 on 2025-01-01 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_alter_player_category_alter_postih_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_room_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='category',
            field=models.CharField(choices=[('1-BEZ', 'Bezpartijní'), ('3-KOM', 'Člen Strany'), ('4-POS', 'Poslanec'), ('2-KAN', 'Kandidát'), ('7-GEN', 'Generální Tajemník ÚV Strany'), ('6-POL', 'Člen Politbyra ÚV'), ('5-UV', 'Člen Ústředního Výboru')], default='1-BEZ', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='postih',
            name='category',
            field=models.CharField(choices=[('1-BEZ', 'Bezpartijní'), ('3-KOM', 'Člen Strany'), ('4-POS', 'Poslanec'), ('2-KAN', 'Kandidát'), ('7-GEN', 'Generální Tajemník ÚV Strany'), ('6-POL', 'Člen Politbyra ÚV'), ('5-UV', 'Člen Ústředního Výboru')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='actual_player',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='vylepseni',
            name='category',
            field=models.CharField(choices=[('1-BEZ', 'Bezpartijní'), ('3-KOM', 'Člen Strany'), ('4-POS', 'Poslanec'), ('2-KAN', 'Kandidát'), ('7-GEN', 'Generální Tajemník ÚV Strany'), ('6-POL', 'Člen Politbyra ÚV'), ('5-UV', 'Člen Ústředního Výboru')], max_length=200, null=True),
        ),
    ]
