# Generated by Django 4.2.17 on 2025-01-02 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_remove_postih_code_remove_vylepseni_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='header',
        ),
        migrations.RemoveField(
            model_name='message',
            name='player',
        ),
        migrations.AddField(
            model_name='message',
            name='reciever',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.player'),
        ),
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='category',
            field=models.CharField(choices=[('3-KOM', 'Člen Strany'), ('7-GEN', 'Generální Tajemník ÚV Strany'), ('6-POL', 'Člen Politbyra ÚV'), ('5-UV', 'Člen Ústředního Výboru'), ('1-BEZ', 'Bezpartijní'), ('2-KAN', 'Kandidát'), ('4-POS', 'Poslanec')], default='1-BEZ', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='postih',
            name='category',
            field=models.CharField(choices=[('3-KOM', 'Člen Strany'), ('7-GEN', 'Generální Tajemník ÚV Strany'), ('6-POL', 'Člen Politbyra ÚV'), ('5-UV', 'Člen Ústředního Výboru'), ('1-BEZ', 'Bezpartijní'), ('2-KAN', 'Kandidát'), ('4-POS', 'Poslanec')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vylepseni',
            name='category',
            field=models.CharField(choices=[('3-KOM', 'Člen Strany'), ('7-GEN', 'Generální Tajemník ÚV Strany'), ('6-POL', 'Člen Politbyra ÚV'), ('5-UV', 'Člen Ústředního Výboru'), ('1-BEZ', 'Bezpartijní'), ('2-KAN', 'Kandidát'), ('4-POS', 'Poslanec')], max_length=200, null=True),
        ),
    ]
