# Generated by Django 4.2.17 on 2025-01-03 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_remove_message_header_remove_message_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.room'),
        ),
        migrations.AlterField(
            model_name='message',
            name='reciever',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='category',
            field=models.CharField(choices=[('2-KAN', 'Kandidát'), ('1-BEZ', 'Bezpartijní'), ('7-GEN', 'Generální Tajemník ÚV Strany'), ('5-UV', 'Člen Ústředního Výboru'), ('6-POL', 'Člen Politbyra ÚV'), ('3-KOM', 'Člen Strany'), ('4-POS', 'Poslanec')], default='1-BEZ', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='postih',
            name='category',
            field=models.CharField(choices=[('2-KAN', 'Kandidát'), ('1-BEZ', 'Bezpartijní'), ('7-GEN', 'Generální Tajemník ÚV Strany'), ('5-UV', 'Člen Ústředního Výboru'), ('6-POL', 'Člen Politbyra ÚV'), ('3-KOM', 'Člen Strany'), ('4-POS', 'Poslanec')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vylepseni',
            name='category',
            field=models.CharField(choices=[('2-KAN', 'Kandidát'), ('1-BEZ', 'Bezpartijní'), ('7-GEN', 'Generální Tajemník ÚV Strany'), ('5-UV', 'Člen Ústředního Výboru'), ('6-POL', 'Člen Politbyra ÚV'), ('3-KOM', 'Člen Strany'), ('4-POS', 'Poslanec')], max_length=200, null=True),
        ),
    ]
