# Generated by Django 4.2.17 on 2025-01-03 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_message_room_alter_message_reciever_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='reciever',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.player'),
        ),
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.room'),
        ),
        migrations.AlterField(
            model_name='player',
            name='category',
            field=models.CharField(choices=[('3-KOM', 'Člen Strany'), ('6-POL', 'Člen Politbyra ÚV'), ('2-KAN', 'Kandidát'), ('4-POS', 'Poslanec'), ('5-UV', 'Člen Ústředního Výboru'), ('1-BEZ', 'Bezpartijní'), ('7-GEN', 'Generální Tajemník ÚV Strany')], default='1-BEZ', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='postih',
            name='category',
            field=models.CharField(choices=[('3-KOM', 'Člen Strany'), ('6-POL', 'Člen Politbyra ÚV'), ('2-KAN', 'Kandidát'), ('4-POS', 'Poslanec'), ('5-UV', 'Člen Ústředního Výboru'), ('1-BEZ', 'Bezpartijní'), ('7-GEN', 'Generální Tajemník ÚV Strany')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vylepseni',
            name='category',
            field=models.CharField(choices=[('3-KOM', 'Člen Strany'), ('6-POL', 'Člen Politbyra ÚV'), ('2-KAN', 'Kandidát'), ('4-POS', 'Poslanec'), ('5-UV', 'Člen Ústředního Výboru'), ('1-BEZ', 'Bezpartijní'), ('7-GEN', 'Generální Tajemník ÚV Strany')], max_length=200, null=True),
        ),
    ]
