# Generated by Django 4.2.17 on 2025-01-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_alter_message_reciever_alter_message_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='category',
            field=models.CharField(choices=[('7-GEN', 'Generální Tajemník ÚV Strany'), ('4-POS', 'Poslanec'), ('2-KAN', 'Kandidát'), ('5-UV', 'Člen Ústředního Výboru'), ('3-KOM', 'Člen Strany'), ('1-BEZ', 'Bezpartijní'), ('6-POL', 'Člen Politbyra ÚV')], default='1-BEZ', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='postih',
            name='category',
            field=models.CharField(choices=[('7-GEN', 'Generální Tajemník ÚV Strany'), ('4-POS', 'Poslanec'), ('2-KAN', 'Kandidát'), ('5-UV', 'Člen Ústředního Výboru'), ('3-KOM', 'Člen Strany'), ('1-BEZ', 'Bezpartijní'), ('6-POL', 'Člen Politbyra ÚV')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vylepseni',
            name='category',
            field=models.CharField(choices=[('7-GEN', 'Generální Tajemník ÚV Strany'), ('4-POS', 'Poslanec'), ('2-KAN', 'Kandidát'), ('5-UV', 'Člen Ústředního Výboru'), ('3-KOM', 'Člen Strany'), ('1-BEZ', 'Bezpartijní'), ('6-POL', 'Člen Politbyra ÚV')], max_length=200, null=True),
        ),
    ]
