# Generated by Django 4.2.17 on 2025-01-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_message_created_at_alter_player_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='room_join',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='category',
            field=models.CharField(choices=[('5-UV', 'Člen Ústředního Výboru'), ('2-KAN', 'Kandidát'), ('1-BEZ', 'Bezpartijní'), ('3-KOM', 'Člen Strany'), ('4-POS', 'Poslanec'), ('7-GEN', 'Generální Tajemník ÚV Strany'), ('6-POL', 'Člen Politbyra ÚV')], default='1-BEZ', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='postih',
            name='category',
            field=models.CharField(choices=[('5-UV', 'Člen Ústředního Výboru'), ('2-KAN', 'Kandidát'), ('1-BEZ', 'Bezpartijní'), ('3-KOM', 'Člen Strany'), ('4-POS', 'Poslanec'), ('7-GEN', 'Generální Tajemník ÚV Strany'), ('6-POL', 'Člen Politbyra ÚV')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vylepseni',
            name='category',
            field=models.CharField(choices=[('5-UV', 'Člen Ústředního Výboru'), ('2-KAN', 'Kandidát'), ('1-BEZ', 'Bezpartijní'), ('3-KOM', 'Člen Strany'), ('4-POS', 'Poslanec'), ('7-GEN', 'Generální Tajemník ÚV Strany'), ('6-POL', 'Člen Politbyra ÚV')], max_length=200, null=True),
        ),
    ]
