# Generated by Django 4.2.17 on 2025-01-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_player_room_join_alter_player_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='room_join',
        ),
        migrations.AlterField(
            model_name='player',
            name='category',
            field=models.CharField(choices=[('5-UV', 'Člen Ústředního Výboru'), ('3-KOM', 'Člen Strany'), ('7-GEN', 'Generální Tajemník ÚV Strany'), ('4-POS', 'Poslanec'), ('2-KAN', 'Kandidát'), ('1-BEZ', 'Bezpartijní'), ('6-POL', 'Člen Politbyra ÚV')], default='1-BEZ', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='postih',
            name='category',
            field=models.CharField(choices=[('5-UV', 'Člen Ústředního Výboru'), ('3-KOM', 'Člen Strany'), ('7-GEN', 'Generální Tajemník ÚV Strany'), ('4-POS', 'Poslanec'), ('2-KAN', 'Kandidát'), ('1-BEZ', 'Bezpartijní'), ('6-POL', 'Člen Politbyra ÚV')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vylepseni',
            name='category',
            field=models.CharField(choices=[('5-UV', 'Člen Ústředního Výboru'), ('3-KOM', 'Člen Strany'), ('7-GEN', 'Generální Tajemník ÚV Strany'), ('4-POS', 'Poslanec'), ('2-KAN', 'Kandidát'), ('1-BEZ', 'Bezpartijní'), ('6-POL', 'Člen Politbyra ÚV')], max_length=200, null=True),
        ),
    ]
