# Generated by Django 4.2.17 on 2025-01-04 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_remove_player_room_join_alter_player_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Notification',
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterField(
            model_name='player',
            name='category',
            field=models.CharField(choices=[('4-POS', 'Poslanec'), ('7-GEN', 'Generální Tajemník ÚV Strany'), ('1-BEZ', 'Bezpartijní'), ('2-KAN', 'Kandidát'), ('6-POL', 'Člen Politbyra ÚV'), ('3-KOM', 'Člen Strany'), ('5-UV', 'Člen Ústředního Výboru')], default='1-BEZ', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='postih',
            name='category',
            field=models.CharField(choices=[('4-POS', 'Poslanec'), ('7-GEN', 'Generální Tajemník ÚV Strany'), ('1-BEZ', 'Bezpartijní'), ('2-KAN', 'Kandidát'), ('6-POL', 'Člen Politbyra ÚV'), ('3-KOM', 'Člen Strany'), ('5-UV', 'Člen Ústředního Výboru')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vylepseni',
            name='category',
            field=models.CharField(choices=[('4-POS', 'Poslanec'), ('7-GEN', 'Generální Tajemník ÚV Strany'), ('1-BEZ', 'Bezpartijní'), ('2-KAN', 'Kandidát'), ('6-POL', 'Člen Politbyra ÚV'), ('3-KOM', 'Člen Strany'), ('5-UV', 'Člen Ústředního Výboru')], max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.room')),
            ],
            options={
                'verbose_name': 'History Record',
                'verbose_name_plural': 'History Records',
            },
        ),
    ]
