# Generated by Django 4.2.17 on 2025-01-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_rename_message_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_notification_read',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='category',
            field=models.CharField(choices=[('1-BEZ', 'Bezpartijní'), ('7-GEN', 'Generální Tajemník ÚV Strany'), ('5-UV', 'Člen Ústředního Výboru'), ('3-KOM', 'Člen Strany'), ('4-POS', 'Poslanec'), ('6-POL', 'Člen Politbyra ÚV'), ('2-KAN', 'Kandidát')], default='1-BEZ', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='postih',
            name='category',
            field=models.CharField(choices=[('1-BEZ', 'Bezpartijní'), ('7-GEN', 'Generální Tajemník ÚV Strany'), ('5-UV', 'Člen Ústředního Výboru'), ('3-KOM', 'Člen Strany'), ('4-POS', 'Poslanec'), ('6-POL', 'Člen Politbyra ÚV'), ('2-KAN', 'Kandidát')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vylepseni',
            name='category',
            field=models.CharField(choices=[('1-BEZ', 'Bezpartijní'), ('7-GEN', 'Generální Tajemník ÚV Strany'), ('5-UV', 'Člen Ústředního Výboru'), ('3-KOM', 'Člen Strany'), ('4-POS', 'Poslanec'), ('6-POL', 'Člen Politbyra ÚV'), ('2-KAN', 'Kandidát')], max_length=200, null=True),
        ),
    ]
