# Generated by Django 4.2.17 on 2025-01-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_player_last_notification_read_alter_player_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='joined_room_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='category',
            field=models.CharField(choices=[('3-KOM', 'Člen Strany'), ('6-POL', 'Člen Politbyra ÚV'), ('5-UV', 'Člen Ústředního Výboru'), ('2-KAN', 'Kandidát'), ('7-GEN', 'Generální Tajemník ÚV Strany'), ('4-POS', 'Poslanec'), ('1-BEZ', 'Bezpartijní')], default='1-BEZ', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='postih',
            name='category',
            field=models.CharField(choices=[('3-KOM', 'Člen Strany'), ('6-POL', 'Člen Politbyra ÚV'), ('5-UV', 'Člen Ústředního Výboru'), ('2-KAN', 'Kandidát'), ('7-GEN', 'Generální Tajemník ÚV Strany'), ('4-POS', 'Poslanec'), ('1-BEZ', 'Bezpartijní')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vylepseni',
            name='category',
            field=models.CharField(choices=[('3-KOM', 'Člen Strany'), ('6-POL', 'Člen Politbyra ÚV'), ('5-UV', 'Člen Ústředního Výboru'), ('2-KAN', 'Kandidát'), ('7-GEN', 'Generální Tajemník ÚV Strany'), ('4-POS', 'Poslanec'), ('1-BEZ', 'Bezpartijní')], max_length=200, null=True),
        ),
    ]
