# Generated by Django 4.2.17 on 2025-01-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0028_remove_history_joined_room_at_player_joined_room_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='category',
            field=models.CharField(choices=[('7-GEN', 'Generální Tajemník ÚV Strany'), ('5-UV', 'Člen Ústředního Výboru'), ('6-POL', 'Člen Politbyra ÚV'), ('1-BEZ', 'Bezpartijní'), ('2-KAN', 'Kandidát'), ('3-KOM', 'Člen Strany'), ('4-POS', 'Poslanec')], default='1-BEZ', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='postih',
            name='category',
            field=models.CharField(choices=[('7-GEN', 'Generální Tajemník ÚV Strany'), ('5-UV', 'Člen Ústředního Výboru'), ('6-POL', 'Člen Politbyra ÚV'), ('1-BEZ', 'Bezpartijní'), ('2-KAN', 'Kandidát'), ('3-KOM', 'Člen Strany'), ('4-POS', 'Poslanec')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vylepseni',
            name='category',
            field=models.CharField(choices=[('7-GEN', 'Generální Tajemník ÚV Strany'), ('5-UV', 'Člen Ústředního Výboru'), ('6-POL', 'Člen Politbyra ÚV'), ('1-BEZ', 'Bezpartijní'), ('2-KAN', 'Kandidát'), ('3-KOM', 'Člen Strany'), ('4-POS', 'Poslanec')], max_length=200, null=True),
        ),
    ]
