# Generated by Django 4.2.17 on 2025-01-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0029_alter_player_category_alter_postih_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='category',
            field=models.CharField(choices=[('2-KAN', 'Kandidát'), ('5-UV', 'Člen Ústředního Výboru'), ('3-KOM', 'Člen Strany'), ('6-POL', 'Člen Politbyra ÚV'), ('4-POS', 'Poslanec'), ('1-BEZ', 'Bezpartijní'), ('7-GEN', 'Generální Tajemník ÚV Strany')], default='1-BEZ', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='postih',
            name='category',
            field=models.CharField(choices=[('2-KAN', 'Kandidát'), ('5-UV', 'Člen Ústředního Výboru'), ('3-KOM', 'Člen Strany'), ('6-POL', 'Člen Politbyra ÚV'), ('4-POS', 'Poslanec'), ('1-BEZ', 'Bezpartijní'), ('7-GEN', 'Generální Tajemník ÚV Strany')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vylepseni',
            name='category',
            field=models.CharField(choices=[('2-KAN', 'Kandidát'), ('5-UV', 'Člen Ústředního Výboru'), ('3-KOM', 'Člen Strany'), ('6-POL', 'Člen Politbyra ÚV'), ('4-POS', 'Poslanec'), ('1-BEZ', 'Bezpartijní'), ('7-GEN', 'Generální Tajemník ÚV Strany')], max_length=200, null=True),
        ),
    ]
