# Generated by Django 4.2.17 on 2025-01-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0030_alter_player_category_alter_postih_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cube_size', models.IntegerField(default=6)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='player',
            name='category',
            field=models.CharField(choices=[('6-POL', 'Člen Politbyra ÚV'), ('5-UV', 'Člen Ústředního Výboru'), ('1-BEZ', 'Bezpartijní'), ('4-POS', 'Poslanec'), ('2-KAN', 'Kandidát'), ('7-GEN', 'Generální Tajemník ÚV Strany'), ('3-KOM', 'Člen Strany')], default='1-BEZ', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='postih',
            name='category',
            field=models.CharField(choices=[('6-POL', 'Člen Politbyra ÚV'), ('5-UV', 'Člen Ústředního Výboru'), ('1-BEZ', 'Bezpartijní'), ('4-POS', 'Poslanec'), ('2-KAN', 'Kandidát'), ('7-GEN', 'Generální Tajemník ÚV Strany'), ('3-KOM', 'Člen Strany')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vylepseni',
            name='category',
            field=models.CharField(choices=[('6-POL', 'Člen Politbyra ÚV'), ('5-UV', 'Člen Ústředního Výboru'), ('1-BEZ', 'Bezpartijní'), ('4-POS', 'Poslanec'), ('2-KAN', 'Kandidát'), ('7-GEN', 'Generální Tajemník ÚV Strany'), ('3-KOM', 'Člen Strany')], max_length=200, null=True),
        ),
    ]
