# Generated by Django 4.2.17 on 2025-01-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0031_config_alter_player_category_alter_postih_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='type',
            field=models.CharField(default='dice', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(default='dice', max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='category',
            field=models.CharField(choices=[('7-GEN', 'Generální Tajemník ÚV Strany'), ('5-UV', 'Člen Ústředního Výboru'), ('4-POS', 'Poslanec'), ('1-BEZ', 'Bezpartijní'), ('2-KAN', 'Kandidát'), ('3-KOM', 'Člen Strany'), ('6-POL', 'Člen Politbyra ÚV')], default='1-BEZ', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='postih',
            name='category',
            field=models.CharField(choices=[('7-GEN', 'Generální Tajemník ÚV Strany'), ('5-UV', 'Člen Ústředního Výboru'), ('4-POS', 'Poslanec'), ('1-BEZ', 'Bezpartijní'), ('2-KAN', 'Kandidát'), ('3-KOM', 'Člen Strany'), ('6-POL', 'Člen Politbyra ÚV')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vylepseni',
            name='category',
            field=models.CharField(choices=[('7-GEN', 'Generální Tajemník ÚV Strany'), ('5-UV', 'Člen Ústředního Výboru'), ('4-POS', 'Poslanec'), ('1-BEZ', 'Bezpartijní'), ('2-KAN', 'Kandidát'), ('3-KOM', 'Člen Strany'), ('6-POL', 'Člen Politbyra ÚV')], max_length=200, null=True),
        ),
    ]
