# Generated by Django 4.2.17 on 2025-01-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0033_effect_delete_postih_delete_vylepseni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='effect',
            name='go_to_start',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='effect',
            name='category',
            field=models.CharField(choices=[('5-UV', 'Člen Ústředního Výboru'), ('3-KOM', 'Člen Strany'), ('7-GEN', 'Generální Tajemník ÚV Strany'), ('6-POL', 'Člen Politbyra ÚV'), ('1-BEZ', 'Bezpartijní'), ('2-KAN', 'Kandidát'), ('4-POS', 'Poslanec')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='category',
            field=models.CharField(choices=[('5-UV', 'Člen Ústředního Výboru'), ('3-KOM', 'Člen Strany'), ('7-GEN', 'Generální Tajemník ÚV Strany'), ('6-POL', 'Člen Politbyra ÚV'), ('1-BEZ', 'Bezpartijní'), ('2-KAN', 'Kandidát'), ('4-POS', 'Poslanec')], default='1-BEZ', max_length=200, null=True),
        ),
    ]
