# Generated by Django 4.2.17 on 2025-01-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0034_effect_go_to_start_alter_effect_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='cube_size',
        ),
        migrations.AddField(
            model_name='config',
            name='char',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='effect',
            name='category',
            field=models.CharField(choices=[('3-KOM', 'Člen Strany'), ('1-BEZ', 'Bezpartijní'), ('5-UV', 'Člen Ústředního Výboru'), ('4-POS', 'Poslanec'), ('6-POL', 'Člen Politbyra ÚV'), ('7-GEN', 'Generální Tajemník ÚV Strany'), ('2-KAN', 'Kandidát')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='category',
            field=models.CharField(choices=[('3-KOM', 'Člen Strany'), ('1-BEZ', 'Bezpartijní'), ('5-UV', 'Člen Ústředního Výboru'), ('4-POS', 'Poslanec'), ('6-POL', 'Člen Politbyra ÚV'), ('7-GEN', 'Generální Tajemník ÚV Strany'), ('2-KAN', 'Kandidát')], default='1-BEZ', max_length=200, null=True),
        ),
    ]
