# Generated by Django 4.2.17 on 2025-01-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0035_remove_config_cube_size_config_char_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effect',
            name='category',
            field=models.CharField(choices=[('3-KOM', 'Člen Strany'), ('7-GEN', 'Generální Tajemník ÚV Strany'), ('1-BEZ', 'Bezpartijní'), ('5-UV', 'Člen Ústředního Výboru'), ('6-POL', 'Člen Politbyra ÚV'), ('4-POS', 'Poslanec'), ('2-KAN', 'Kandidát')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='effect',
            name='type',
            field=models.CharField(choices=[('happy', 'Vylepšení'), ('sad', 'Postih')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='category',
            field=models.CharField(choices=[('3-KOM', 'Člen Strany'), ('7-GEN', 'Generální Tajemník ÚV Strany'), ('1-BEZ', 'Bezpartijní'), ('5-UV', 'Člen Ústředního Výboru'), ('6-POL', 'Člen Politbyra ÚV'), ('4-POS', 'Poslanec'), ('2-KAN', 'Kandidát')], default='1-BEZ', max_length=200, null=True),
        ),
    ]
