# Generated by Django 4.2.17 on 2025-01-09 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0039_alter_effect_category_alter_player_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Config',
        ),
        migrations.AlterField(
            model_name='effect',
            name='category',
            field=models.CharField(choices=[('2-KAN', 'Kandidát'), ('6-POL', 'Člen Politbyra ÚV'), ('4-POS', 'Poslanec'), ('3-KOM', 'Člen Strany'), ('7-GEN', 'Generální Tajemník ÚV Strany'), ('1-BEZ', 'Bezpartijní'), ('5-UV', 'Člen Ústředního Výboru')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='category',
            field=models.CharField(choices=[('2-KAN', 'Kandidát'), ('6-POL', 'Člen Politbyra ÚV'), ('4-POS', 'Poslanec'), ('3-KOM', 'Člen Strany'), ('7-GEN', 'Generální Tajemník ÚV Strany'), ('1-BEZ', 'Bezpartijní'), ('5-UV', 'Člen Ústředního Výboru')], default='1-BEZ', max_length=200, null=True),
        ),
    ]
