# Generated by Django 4.2.17 on 2025-01-09 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0040_delete_config_alter_effect_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effect',
            name='category',
            field=models.CharField(choices=[('5-UV', 'Člen Ústředního Výboru'), ('4-POS', 'Poslanec'), ('7-GEN', 'Generální Tajemník ÚV Strany'), ('1-BEZ', 'Bezpartijní'), ('3-KOM', 'Člen Strany'), ('2-KAN', 'Kandidát'), ('6-POL', 'Člen Politbyra ÚV')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='effect',
            name='type',
            field=models.CharField(choices=[('sad', 'Postih'), ('happy', 'Vylepšení')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='category',
            field=models.CharField(choices=[('5-UV', 'Člen Ústředního Výboru'), ('4-POS', 'Poslanec'), ('7-GEN', 'Generální Tajemník ÚV Strany'), ('1-BEZ', 'Bezpartijní'), ('3-KOM', 'Člen Strany'), ('2-KAN', 'Kandidát'), ('6-POL', 'Člen Politbyra ÚV')], default='1-BEZ', max_length=200, null=True),
        ),
    ]
