# Generated by Django 4.2.17 on 2025-01-10 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0041_alter_effect_category_alter_effect_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effect',
            name='category',
            field=models.CharField(choices=[('2-KAN', 'Kandidát'), ('3-KOM', 'Člen Strany'), ('7-GEN', 'Generální Tajemník ÚV Strany'), ('4-POS', 'Poslanec'), ('1-BEZ', 'Bezpartijní'), ('6-POL', 'Člen Politbyra ÚV'), ('5-UV', 'Člen Ústředního Výboru')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='category',
            field=models.CharField(choices=[('2-KAN', 'Kandidát'), ('3-KOM', 'Člen Strany'), ('7-GEN', 'Generální Tajemník ÚV Strany'), ('4-POS', 'Poslanec'), ('1-BEZ', 'Bezpartijní'), ('6-POL', 'Člen Politbyra ÚV'), ('5-UV', 'Člen Ústředního Výboru')], default='1-BEZ', max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=2000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.player')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.room')),
            ],
            options={
                'verbose_name': 'Zpráva v chatu',
                'verbose_name_plural': 'Zprávy v chatu',
            },
        ),
    ]
