# Generated by Django 4.2.17 on 2025-01-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0042_alter_effect_category_alter_player_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='effect',
            name='money_change_by_if_stalin',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='effect',
            name='category',
            field=models.CharField(choices=[('3-KOM', 'Člen Strany'), ('6-POL', 'Člen Politbyra ÚV'), ('5-UV', 'Člen Ústředního Výboru'), ('4-POS', 'Poslanec'), ('7-GEN', 'Generální Tajemník ÚV Strany'), ('2-KAN', 'Kandidát'), ('1-BEZ', 'Bezpartijní')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='category',
            field=models.CharField(choices=[('3-KOM', 'Člen Strany'), ('6-POL', 'Člen Politbyra ÚV'), ('5-UV', 'Člen Ústředního Výboru'), ('4-POS', 'Poslanec'), ('7-GEN', 'Generální Tajemník ÚV Strany'), ('2-KAN', 'Kandidát'), ('1-BEZ', 'Bezpartijní')], default='1-BEZ', max_length=200, null=True),
        ),
    ]
