# Generated by Django 4.2.17 on 2025-01-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0043_effect_money_change_by_if_stalin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='effect',
            name='history_record_message_p1_if_stalin',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='effect',
            name='history_record_message_p2_if_stalin',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='effect',
            name='notification_message_if_stalin',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='effect',
            name='category',
            field=models.CharField(choices=[('4-POS', 'Poslanec'), ('2-KAN', 'Kandidát'), ('6-POL', 'Člen Politbyra ÚV'), ('1-BEZ', 'Bezpartijní'), ('7-GEN', 'Generální Tajemník ÚV Strany'), ('3-KOM', 'Člen Strany'), ('5-UV', 'Člen Ústředního Výboru')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='category',
            field=models.CharField(choices=[('4-POS', 'Poslanec'), ('2-KAN', 'Kandidát'), ('6-POL', 'Člen Politbyra ÚV'), ('1-BEZ', 'Bezpartijní'), ('7-GEN', 'Generální Tajemník ÚV Strany'), ('3-KOM', 'Člen Strany'), ('5-UV', 'Člen Ústředního Výboru')], default='1-BEZ', max_length=200, null=True),
        ),
    ]
