# Generated by Django 4.2.17 on 2025-01-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0044_effect_history_record_message_p1_if_stalin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effect',
            name='category',
            field=models.CharField(choices=[('3-KOM', 'Člen Strany'), ('5-UV', 'Člen Ústředního Výboru'), ('4-POS', 'Poslanec'), ('1-BEZ', 'Bezpartijní'), ('7-GEN', 'Generální Tajemník ÚV Strany'), ('6-POL', 'Člen Politbyra ÚV'), ('2-KAN', 'Kandidát')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='category',
            field=models.CharField(choices=[('3-KOM', 'Člen Strany'), ('5-UV', 'Člen Ústředního Výboru'), ('4-POS', 'Poslanec'), ('1-BEZ', 'Bezpartijní'), ('7-GEN', 'Generální Tajemník ÚV Strany'), ('6-POL', 'Člen Politbyra ÚV'), ('2-KAN', 'Kandidát')], default='1-BEZ', max_length=200, null=True),
        ),
    ]
