# Generated by Django 4.2.17 on 2025-01-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0045_alter_effect_category_alter_player_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effect',
            name='category',
            field=models.CharField(choices=[('2-KAN', 'Kandidát'), ('6-POL', 'Člen Politbyra ÚV'), ('3-KOM', 'Člen Strany'), ('5-UV', 'Člen Ústředního Výboru'), ('1-BEZ', 'Bezpartijní'), ('7-GEN', 'Generální Tajemník ÚV Strany'), ('4-POS', 'Poslanec')], help_text='pro jakou kategorii se využije', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='effect',
            name='give_everybody',
            field=models.IntegerField(default=0, help_text='množství peněz, které se přidají každému hráči, krom tohoto (kladné číslo)', null=True),
        ),
        migrations.AlterField(
            model_name='effect',
            name='give_nuzky',
            field=models.BooleanField(default=False, help_text='hráč získá nůžky na ostnatý drát'),
        ),
        migrations.AlterField(
            model_name='effect',
            name='give_plan_zaminovani',
            field=models.BooleanField(default=False, help_text='hráč získá plán zaminování'),
        ),
        migrations.AlterField(
            model_name='effect',
            name='give_propustka',
            field=models.BooleanField(default=False, help_text='hráč získá propustku z vězení'),
        ),
        migrations.AlterField(
            model_name='effect',
            name='give_proverka',
            field=models.BooleanField(default=False, help_text='hráč získá jednu automaticky splněnou stranickou prověrku'),
        ),
        migrations.AlterField(
            model_name='effect',
            name='give_stalin',
            field=models.BooleanField(default=False, help_text='hráč odteď po zbytek hry vypadá jako Stalin'),
        ),
        migrations.AlterField(
            model_name='effect',
            name='give_vesta',
            field=models.BooleanField(default=False, help_text='hráč získá neprůstřelnou vestu'),
        ),
        migrations.AlterField(
            model_name='effect',
            name='go_to_blazinec',
            field=models.BooleanField(default=False, help_text='pošle hráče rovnou do blázince a ztratí veškeré oběživo'),
        ),
        migrations.AlterField(
            model_name='effect',
            name='go_to_start',
            field=models.BooleanField(default=False, help_text='pošle hráče na start ale neztratí oběživo'),
        ),
        migrations.AlterField(
            model_name='effect',
            name='go_to_vezeni',
            field=models.BooleanField(default=False, help_text='pošle hráče rovnou do vězení a ztratí vešekeré oběživo'),
        ),
        migrations.AlterField(
            model_name='effect',
            name='history_record_message_p1',
            field=models.CharField(blank=True, help_text='první část zprávy v herním deníku, po ní bude automaticky přidána mezera, jméno hráče a mezera', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='effect',
            name='history_record_message_p1_if_stalin',
            field=models.CharField(blank=True, help_text='pokud je vyplněno a pokud hráč vypadá jako Stalin, není použita první polovina zprávy v herním deníku (musí být vyplněna), ale tato', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='effect',
            name='history_record_message_p2',
            field=models.CharField(blank=True, help_text='druhá část zprávy v herním deníku, před ní je jméno hráče a mezera automaticky', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='effect',
            name='history_record_message_p2_if_stalin',
            field=models.CharField(blank=True, help_text='pokud je vyplněno a pokud hráč vypadá jako Stalin, není použita druhá polovina zprávy v herním deníku (musí být vyplněna), ale tato', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='effect',
            name='money_change_by',
            field=models.IntegerField(default=0, help_text='o kolik se změní peníze hráče (záporné číslo odečte)', null=True),
        ),
        migrations.AlterField(
            model_name='effect',
            name='money_change_by_if_stalin',
            field=models.IntegerField(default=0, help_text='pokud je vyplněno a pokud hráč vypadá jako Stalin, nezíská money_change by (musí být vyplněno), ale tyto peníze (záporné číslo je odečte)', null=True),
        ),
        migrations.AlterField(
            model_name='effect',
            name='money_change_by_per_player',
            field=models.IntegerField(default=0, help_text='množství peněz, kteté získá tento hráč za každého dalšího hráče v místnosti (záporné číslo je odečte)', null=True),
        ),
        migrations.AlterField(
            model_name='effect',
            name='notification_message',
            field=models.CharField(blank=True, help_text='oznámení, které uživateli přijde', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='effect',
            name='notification_message_if_stalin',
            field=models.CharField(blank=True, help_text='pokud je vyplněno a pokud hráč vypadá jako Stalin, není zobrazena běžná notifikace (musí být vyplněna), ale tato', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='effect',
            name='pindex_change_by',
            field=models.IntegerField(default=0, help_text='o kolik se změní políčko hráče (záporné číslo dozadu)', null=True),
        ),
        migrations.AlterField(
            model_name='effect',
            name='pindex_set_to',
            field=models.IntegerField(default=0, help_text='na jaké políčko je hráč přesunut (nelze použít políčka 0, 1000 a 1001)', null=True),
        ),
        migrations.AlterField(
            model_name='effect',
            name='remove_from_everybody',
            field=models.IntegerField(default=0, help_text='množství peněz, které se odečte každému hráči, krom tohoto (kladné číslo)', null=True),
        ),
        migrations.AlterField(
            model_name='effect',
            name='type',
            field=models.CharField(choices=[('happy', 'Vylepšení'), ('sad', 'Postih')], help_text='postih nebo vylepšení', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='effect',
            name='wait_moves_set_to',
            field=models.IntegerField(default=0, help_text='kolik kol hráč nehraje (je přeskočen)', null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='category',
            field=models.CharField(choices=[('2-KAN', 'Kandidát'), ('6-POL', 'Člen Politbyra ÚV'), ('3-KOM', 'Člen Strany'), ('5-UV', 'Člen Ústředního Výboru'), ('1-BEZ', 'Bezpartijní'), ('7-GEN', 'Generální Tajemník ÚV Strany'), ('4-POS', 'Poslanec')], default='1-BEZ', max_length=200, null=True),
        ),
    ]
