# Generated by Django 4.2.17 on 2025-01-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0047_alter_effect_category_alter_effect_give_everybody_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='heading_from',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='effect',
            name='category',
            field=models.CharField(choices=[('1-BEZ', 'Bezpartijní'), ('7-GEN', 'Generální Tajemník ÚV Strany'), ('2-KAN', 'Kandidát'), ('4-POS', 'Poslanec'), ('6-POL', 'Člen Politbyra ÚV'), ('3-KOM', 'Člen Strany'), ('5-UV', 'Člen Ústředního Výboru')], help_text='pro jakou kategorii se využije', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='category',
            field=models.CharField(choices=[('1-BEZ', 'Bezpartijní'), ('7-GEN', 'Generální Tajemník ÚV Strany'), ('2-KAN', 'Kandidát'), ('4-POS', 'Poslanec'), ('6-POL', 'Člen Politbyra ÚV'), ('3-KOM', 'Člen Strany'), ('5-UV', 'Člen Ústředního Výboru')], default='1-BEZ', max_length=200, null=True),
        ),
    ]
